sensor.studio_multisensor_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.studio_multisensor_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.studio_multisensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.studio_multisensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
