################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:

    ################################################
    ## Binary Sensor
    ################################################
    # ISY-994 door sensor component converts the
    # heartbeat into a low battery by going high
    # when the hearbeat is missed
    binary_sensor.studio_front_door_sensor:
      friendly_name: "Studio Front Door"
      device_class: door
    binary_sensor.studio_front_door_sensor_hb:
      friendly_name: "Studio Front Door Sensor Battery"
      device_class: battery
    binary_sensor.studio_motion_sensor_lb:
      friendly_name: "Studio Motion Sensor Battery"
      device_class: battery
    binary_sensor.studio_bath_motion_sensor_lb:
      friendly_name: "Studio Bathroom Motion Sensor Battery"
      device_class: battery

    ################################################
    ## Light
    ################################################
    light.studio_chandeliers:
      friendly_name: "Studio Chandeliers"
      icon: mdi:ceiling-light
    light.studio_bed_fan_light:
      friendly_name: "Studio Bedroom Light"
    light.studio_bath_light:
      friendly_name: "Studio Bathroom Light"
    light.studio_kitchen_chandelier:
      friendly_name: "Studio Kitchen Chandelier"
      icon: mdi:ceiling-light
    light.studio_kitchen_sink_lights:
      friendly_name: "Studio Kitchen Sink Lights"
      icon: mdi:ceiling-light
    light.studio_kitchen_cabinet_lights:
      friendly_name: "Studio Kitchen Cabinet Lights"
    light.studio_loft_fan_light:
      friendly_name: "Studio Loft Light"

    ################################################
    ## Switch
    ################################################
    # ISY-994 HA.switch "Program Switches"
    switch.studio_state:                    # 'on' = Home, 'off' = Away
      friendly_name: "Studio Home"
      icon: mdi:home
    switch.studio_shoplight_a:
      friendly_name: "Studio Shoplight A"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_b:
      friendly_name: "Studio Shoplight B"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_c:
      friendly_name: "Studio Shoplight C"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_d:
      friendly_name: "Studio Shoplight D"
      icon: mdi:spotlight-beam

    # ISY-994 scenes
    switch.studio_chandeliers:
      friendly_name: "Studio Chandeliers"
      icon: mdi:ceiling-light
    switch.studio_shoplights:
      friendly_name: "Studio Shoplights"
      icon: mdi:spotlight-beam
    switch.studio_kitchen_lights:
      friendly_name: "Studio Kitchen Lights"
      icon: mdi:lightbulb
    switch.studio_flood_lights:
      friendly_name: "Studio Flood Lights"
      icon: mdi:lightbulb
    switch.studio_flood_lights_front:
      friendly_name: "Studio Flood Lights Front"
      icon: mdi:lightbulb
    switch.studio_flood_light_backs:
      friendly_name: "Studio Flood Lights Back"
      icon: mdi:lightbulb
    switch.studio_porch_lights:
      friendly_name: "Studio Porch Lights"
      icon: mdi:lightbulb
    switch.studio_porch_lights_front:
      friendly_name: "Studio Porch Lights Front"
      icon: mdi:lightbulb

    # ISY-994 switch
    switch.studio_front_porch_light:
      friendly_name: "Porch Light Studio"
      icon: mdi:lightbulb
    switch.studio_front_flood_light:
      friendly_name: "Flood Light Studio Front"
      icon: mdi:lightbulb
    switch.studio_back_flood_light:
      friendly_name: "Flood Light Studio Back"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.studio_bed_fan:
      friendly_name: "Studio Bedroom Fan"
    fan.studio_loft_fan:
      friendly_name: "Studio Loft Fan"
